export const affiliateProducts = [
	// Hotmart Products
	{
		id: 1,
		name: "How to Make Money with AI Tools",
		description:
			"Turn Artificial Intelligence into your best ally to make money online — starting today. Are you curious about how to make money using AI but don't know where to start? This ebook is your quick and practical guide to using the most powerful and beginner-friendly AI tools to create real income from home.",
		category: "Online Courses",
		price: "$4.99",
		originalPrice: "$4.99",
		// discount: "0% OFF",
		image:
			"https://static-media.hotmart.com/-2fW1RAYfiCNvj81noIP7VZ8xxQ=/300x300/smart/filters:format(webp):background_color(white)/hotmart/product_pictures/0b64e02a-d8ce-4cbd-a0e1-1b672be5444f/Howtomakemoney.png?w=920",
		additionalImages: [
			"https://static-media.hotmart.com/-2fW1RAYfiCNvj81noIP7VZ8xxQ=/300x300/smart/filters:format(webp):background_color(white)/hotmart/product_pictures/0b64e02a-d8ce-4cbd-a0e1-1b672be5444f/Howtomakemoney.png?w=920",
			// `https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop`,
			// `https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=800&h=600&fit=crop`,
			// `https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop`,
		],
		affiliateLink: "https://go.hotmart.com/O104195994C?dp=1",
		marketplace: "Digital Products",
		rating: 5,
		reviews: 2,
		tags: ["Ai", "Money", "Beginner Friendly"],
		featured: true,
		commission: "",
		type: "Digital Product",
	},
	{
		id: 2,
		name: "LEARN SPANISH WITH STORIES | COURSE A1-A2",
		description:
			"OUR OPTIMIZED WAY OF LEARNING. Learn like a child with stories and colors. The question-and-answer technique will help you speak easily. Use your senses and learn grammar through colors and images. ----- What will I learn from the course? Vocabulary A2 (800 words) Grammar A2 (present, past, and future tense) How to speak, understand, read and write. You will learn everything you need to master an A2 SPEAKING LEVEL of Spanish. ----- WHO THIS COURSE IS FOR? For all who have no knowledge of the language or are beginners. ----- 92% OF OUR STUDENTS SHOW A HUGE IMPROVEMENT IN JUST ONE MONTH! With each language you speak, you live a new life. The rewards are so big that doors open for a new trip, a new job, or even a new life in a new country. ----- GET STARTED NOW AND MAKE YOUR LIFE AWESOME.",
		category: "Languages",
		price: "$187.00",
		originalPrice: "$187.00",
		// discount: "0% OFF",
		image:
			"https://static-media.hotmart.com/QDrzhlpngge4snhMiFjWk5Vx66M=/300x300/smart/filters:format(webp):background_color(white)/hotmart/product_pictures/d8f4cdfc-74fe-46c2-a5c1-eeaa11b128b1/HotmartA1A2Spanish.png?w=920",
		additionalImages: [
			"https://static-media.hotmart.com/QDrzhlpngge4snhMiFjWk5Vx66M=/300x300/smart/filters:format(webp):background_color(white)/hotmart/product_pictures/d8f4cdfc-74fe-46c2-a5c1-eeaa11b128b1/HotmartA1A2Spanish.png?w=920",
		],
		affiliateLink: "https://go.hotmart.com/L104196642E",
		marketplace: "Digital Products",
		rating: 5.0,
		reviews: 1,
		tags: ["Languages", "Education", "Spanish"],
		featured: false,
		commission: "0%",
		type: "Ebook + Course",
	},

	{
		id: 3,
		name: "“130 Essential French Phrases to Survive Your Trip”(with English and Spanish translation + pronunciation guide)",
		description:
			"Are you traveling to France and don't speak French? This e-book is for you! '130 Essential French Phrases to Survive Your Trip' is a practical and visually clear guide that brings together the most useful expressions to navigate confidently in any French-speaking city. Includes: ✅ 130 phrases organized by topic (restaurants, transportation, emergencies, hotels, etc.) ✅ Translation into English and Spanish ✅ Simplified pronunciation for Spanish speakers (no phonetic skills required!) ✅ Ideal for beginners, travelers, backpackers, or first-time tourists Perfect to carry on your phone or print as a PDF. Become a prepared, polite, and confident tourist!",
		category: "Languages",
		price: "$19.90",
		originalPrice: "$19.90",
		// discount: "0% OFF",
		image:
			"https://static-media.hotmart.com/2CU3IyxhUysg_mVwVTYPVLvxN1w=/filters:background_color(white)/hotmart/product_pictures/85a3c9f0-0dcc-4fa8-9474-b0f6f9e36586/Cortedecabelloendetalle.jpg",
		additionalImages: [
			"https://static-media.hotmart.com/2CU3IyxhUysg_mVwVTYPVLvxN1w=/filters:background_color(white)/hotmart/product_pictures/85a3c9f0-0dcc-4fa8-9474-b0f6f9e36586/Cortedecabelloendetalle.jpg",
		],
		affiliateLink: "https://go.hotmart.com/F104196782X",
		marketplace: "Digital Products",
		rating: 0,
		reviews: 0,
		tags: ["Languages", "French", "Education"],
		featured: true,
		commission: "0%",
		type: "Digital Product",
		primeEligible: false,
	},
	{
		id: 4,
		name: "German Basic Course | Learn German With Stories",
		description:
			"LEARN GERMAN FROM SCRATCH TO LEVEL A2 WITH AN INNOVATIVE METHOD! - In my course, you will reach a basic level (A2) of conversation in German. - Learn everything naturally by listening to Ben's story. - The story-telling method and, in particular, the 'question and answer technique' will help you to reach this goal easily. - Learn spoken grammar with images and colors in our funny stories. - Practice actively the content using the APP Quizlet. - Each course offers a final certification. - Feel more confident when it comes to communicating. GRAMMAR: The alphabet | Conjugation of regular verbs | The nominative | Numbers | Gender rules | Plural | Irregular verbs | Tips on how to learn a language more efficiently | Compound words | The Word 'es' | Formal greeting | The accusative | Word order in main sentences | Separable and inseparable verbs | Modal verbs | The dative | Negation | How to ask questions | Conjunctions | The imperative | Determinant possessive | Demonstrative Pronouns | Indefinite Pronouns | Temporal Adverbs | Accusative prepositions | Dative prepositions | Two-way-prepositions | Present Perfect Tense (Perfekt) | Introduction to the Simple Past (Präteritum) | Introduction to the Comparative. CONVERSATION: Pronunciation rules | How to present yourself | How to make appointments | Using public transportation | Looking for Apartments | Asking / Giving directions | Saying the time and date | Doctor's visit | How to order food in a restaurant. VOCABULARY: Colors | Family | Body | Clothes | At Home | Food and Beverages | Animals | Professions | Weather | Leisure Activities | Emotions and Adjectives | Countries and Languages. COMMENTS 'I'm very happy to have found this course. It is the best course; with the best method, I have experienced so far (I have been studying languages for years). I can say that you can see the love and care that you have put into all this Marcus.' - Sabrina. I HOPE YOU SIGN UP FOR MY COURSE AND BECOME ONE OF MY STUDENTS",
		category: "Languages",
		price: "$64.00",
		originalPrice: "$64.00",
		// discount: "0% OFF",
		image:
			"https://static-media.hotmart.com/ypmedrE55T4sEkg6yK63lZ1SwWU=/300x300/smart/filters:format(webp):background_color(white)/hotmart/product_pictures/f30dd8de-2862-492b-87b0-eabef34e8de1/GermanCourse1TheEasyWayToLearnGerman.jpg?w=920",
		additionalImages: [
			"https://static-media.hotmart.com/ypmedrE55T4sEkg6yK63lZ1SwWU=/300x300/smart/filters:format(webp):background_color(white)/hotmart/product_pictures/f30dd8de-2862-492b-87b0-eabef34e8de1/GermanCourse1TheEasyWayToLearnGerman.jpg?w=920",
		],
		affiliateLink: "https://go.hotmart.com/U104196960I",
		marketplace: "Digital Products",
		rating: 4.8,
		reviews: 4,
		tags: ["Languages", "Education", "German"],
		featured: true,
		commission: "0%",
		type: "Digital Product",
		primeEligible: false,
	},
	// {
	// 	id: 5,
	// 	name: "Python Programming Ebook Collection",
	// 	description:
	// 		"5-in-1 Python programming bundle covering basics to advanced topics and practical projects.",
	// 	category: "Programming Books",
	// 	price: "$29",
	// 	originalPrice: "$97",
	// 	discount: "70% OFF",
	// 	image:
	// 		"https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop",
	// 	additionalImages: [],
	// 	affiliateLink: "https://hotmart.com/python-bundle",
	// 	marketplace: "hotmart",
	// 	rating: 4.6,
	// 	reviews: 892,
	// 	tags: ["Python", "Programming", "Ebook"],
	// 	featured: false,
	// 	commission: "75%",
	// 	type: "Digital Product",
	// },
	// {
	// 	id: 6,
	// 	name: "Apple AirPods Pro (2nd Generation)",
	// 	description:
	// 		"Wireless earbuds with active noise cancellation, spatial audio and MagSafe charging case.",
	// 	category: "Audio",
	// 	price: "$199.99",
	// 	originalPrice: "$249.00",
	// 	discount: "20% OFF",
	// 	image:
	// 		"https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=400&h=300&fit=crop",
	// 	additionalImages: [],
	// 	affiliateLink: "https://amazon.com/airpods-pro",
	// 	marketplace: "amazon",
	// 	rating: 4.7,
	// 	reviews: 45289,
	// 	tags: ["Audio", "Apple", "Wireless"],
	// 	featured: false,
	// 	commission: "1-3%",
	// 	type: "Physical Product",
	// 	primeEligible: true,
	// },
	// {
	// 	id: 7,
	// 	name: "Fitness & Nutrition Complete Program",
	// 	description:
	// 		"12-week fitness and nutrition program with video workouts, meal plans and coaching.",
	// 	category: "Health & Fitness",
	// 	price: "$47",
	// 	originalPrice: "$197",
	// 	discount: "76% OFF",
	// 	image:
	// 		"https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop",
	// 	additionalImages: [],
	// 	affiliateLink: "https://hotmart.com/fitness-program",
	// 	marketplace: "hotmart",
	// 	rating: 4.8,
	// 	reviews: 3245,
	// 	tags: ["Fitness", "Health", "Wellness"],
	// 	featured: true,
	// 	commission: "65%",
	// 	type: "Digital Product",
	// },
	// {
	// 	id: 8,
	// 	name: "Dell UltraSharp 4K Monitor",
	// 	description:
	// 		"27-inch 4K USB-C Hub Monitor with IPS panel and 99% sRGB color coverage.",
	// 	category: "Monitors",
	// 	price: "$549.99",
	// 	originalPrice: "$699.99",
	// 	discount: "21% OFF",
	// 	image:
	// 		"https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=300&fit=crop",
	// 	additionalImages: [],
	// 	affiliateLink: "https://amazon.com/dell-ultrasharp",
	// 	marketplace: "amazon",
	// 	rating: 4.7,
	// 	reviews: 2341,
	// 	tags: ["Monitor", "4K", "Productivity"],
	// 	featured: false,
	// 	commission: "2-4%",
	// 	type: "Physical Product",
	// 	primeEligible: true,
	// },
];

export const categories = [
	"All",
	"Online Courses",
	"Languages",
	"Marketing",
	"Hardware",
	"Storage",
	"Programming Books",
	"Audio",
	"Health & Fitness",
	"Monitors",
];

export const marketplaces = ["All", "Digital Products", "Physical Products"];

export const productTypes = [
	"All",
	"Digital Product",
	"Physical Product",
	"Ebook + Course",
];
